# Generated by Django 4.1.5 on 2023-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201228_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
